require("NvimConfig.plugins.icons")
require("NvimConfig.plugins.undotree")
require("NvimConfig.plugins.catppuccin")
require("NvimConfig.plugins.splashscreen")
require("NvimConfig.plugins.treesitter")
require("NvimConfig.plugins.telescope")
require("NvimConfig.plugins.nvim-cmp")
require("NvimConfig.plugins.lsp")
