vim.g.undotree_TreeVertShape = '│'
vim.g.undotree_TreeSplitShape = '╶╯'
vim.g.undotree_TreeReturnShape = '╶╮'
vim.g.undotree_TreeNodeShape = '╷'
vim.g.undotree_WindowLayout = 2
vim.g.undotree_ShortIndicators = 1
vim.g.undotree_SetFocusWhenToggle = 1
vim.g.undotree_HighlightSyntaxAdd = "SpellRare" 
vim.g.undotree_HighlightSyntaxChange = "SpellLocal"
vim.keymap.set('n', '<leader>u', vim.cmd.UndotreeToggle)
